name=input ("your_first name: ")
surname=input ("your_last name: ")
age=input ("write your age: ")
phone_n=input ("write your phone_number: ")
print("Your firstname ", name,' ' ,"Your last name ", surname)
print ("Your age: " ,age)
print("Your phone_number: ", phone_n)
